package com.newradiogio.model;

public class Country {
    public static final String AF = "AF"; // Afghanistan
    public static final String AL = "AL"; // Albania
    public static final String DZ = "DZ"; // Algeria
    public static final String AS = "AS"; // American Samoa
    public static final String AD = "AD"; // Andorra
    public static final String AO = "AO"; // Angola
    public static final String AI = "AI"; // Anguilla
    public static final String AQ = "AQ"; // Antarctica
    public static final String AG = "AG"; // Antigua and Barbuda
    public static final String AR = "AR"; // Argentina
    public static final String AM = "AM"; // Armenia
    public static final String AW = "AW"; // Aruba
    public static final String AU = "AU"; // Australia
    public static final String AT = "AT"; // Austria
    public static final String AZ = "AZ"; // Azerbaijan
    public static final String BS = "BS"; // Bahamas
    public static final String BH = "BH"; // Bahrain
    public static final String BD = "BD"; // Bangladesh
    public static final String BB = "BB"; // Barbados
    public static final String BY = "BY"; // Belarus
    public static final String BE = "BE"; // Belgium
    public static final String BZ = "BZ"; // Belize
    public static final String BJ = "BJ"; // Benin
    public static final String BM = "BM"; // Bermuda
    public static final String BT = "BT"; // Bhutan
    public static final String BO = "BO"; // Bolivia
    public static final String BA = "BA"; // Bosnia and Herzegovina
    public static final String BW = "BW"; // Botswana
    public static final String BR = "BR"; // Brazil
    public static final String IO = "IO"; // British Indian Ocean Territory
    public static final String VG = "VG"; // British Virgin Islands
    public static final String BN = "BN"; // Brunei
    public static final String BG = "BG"; // Bulgaria
    public static final String BF = "BF"; // Burkina Faso
    public static final String BI = "BI"; // Burundi
    public static final String KH = "KH"; // Cambodia
    public static final String CM = "CM"; // Cameroon
    public static final String CA = "CA"; // Canada
    public static final String CV = "CV"; // Cape Verde
    public static final String KY = "KY"; // Cayman Islands
    public static final String CF = "CF"; // Central African Republic
    public static final String TD = "TD"; // Chad
    public static final String CL = "CL"; // Chile
    public static final String CN = "CN"; // China
    public static final String CX = "CX"; // Christmas Island
    public static final String CC = "CC"; // Cocos Islands
    public static final String CO = "CO"; // Colombia
    public static final String KM = "KM"; // Comoros
    public static final String CK = "CK"; // Cook Islands
    public static final String CR = "CR"; // Costa Rica
    public static final String HR = "HR"; // Croatia
    public static final String CU = "CU"; // Cuba
    public static final String CW = "CW"; // Curacao
    public static final String CY = "CY"; // Cyprus
    public static final String CZ = "CZ"; // Czech Republic
    public static final String CD = "CD"; // Democratic Republic of the Congo
    public static final String DK = "DK"; // Denmark
    public static final String DJ = "DJ"; // Djibouti
    public static final String DM = "DM"; // Dominica
    public static final String DO = "DO"; // Dominican Republic
    public static final String TL = "TL"; // East Timor
    public static final String EC = "EC"; // Ecuador
    public static final String EG = "EG"; // Egypt
    public static final String SV = "SV"; // El Salvador
    public static final String GQ = "GQ"; // Equatorial Guinea
    public static final String ER = "ER"; // Eritrea
    public static final String EE = "EE"; // Estonia
    public static final String ET = "ET"; // Ethiopia
    public static final String FK = "FK"; // Falkland Islands
    public static final String FO = "FO"; // Faroe Islands
    public static final String FJ = "FJ"; // Fiji
    public static final String FI = "FI"; // Finland
    public static final String FR = "FR"; // France
    public static final String PF = "PF"; // French Polynesia
    public static final String GA = "GA"; // Gabon
    public static final String GM = "GM"; // Gambia
    public static final String GE = "GE"; // Georgia
    public static final String DE = "DE"; // Germany
    public static final String GH = "GH"; // Ghana
    public static final String GI = "GI"; // Gibraltar
    public static final String GR = "GR"; // Greece
    public static final String GL = "GL"; // Greenland
    public static final String GD = "GD"; // Grenada
    public static final String GU = "GU"; // Guam
    public static final String GT = "GT"; // Guatemala
    public static final String GG = "GG"; // Guernsey
    public static final String GN = "GN"; // Guinea
    public static final String GW = "GW"; // Guinea-Bissau
    public static final String GY = "GY"; // Guyana
    public static final String HT = "HT"; // Haiti
    public static final String HN = "HN"; // Honduras
    public static final String HK = "HK"; // Hong Kong
    public static final String HU = "HU"; // Hungary
    public static final String IS = "IS"; // Iceland
    public static final String IN = "IN"; // India
    public static final String ID = "ID"; // Indonesia
    public static final String IR = "IR"; // Iran
    public static final String IQ = "IQ"; // Iraq
    public static final String IE = "IE"; // Ireland
    public static final String IM = "IM"; // Isle of Man
    public static final String IL = "IL"; // Israel
    public static final String IT = "IT"; // Italy
    public static final String CI = "CI"; // Ivory Coast
    public static final String JM = "JM"; // Jamaica
    public static final String JP = "JP"; // Japan
    public static final String JE = "JE"; // Jersey
    public static final String JO = "JO"; // Jordan
    public static final String KZ = "KZ"; // Kazakhstan
    public static final String KE = "KE"; // Kenya
    public static final String KI = "KI"; // Kiribati
    public static final String XK = "XK"; // Kosovo
    public static final String KW = "KW"; // Kuwait
    public static final String KG = "KG"; // Kyrgyzstan
    public static final String LA = "LA"; // Laos
    public static final String LV = "LV"; // Latvia
    public static final String LB = "LB"; // Lebanon
    public static final String LS = "LS"; // Lesotho
    public static final String LR = "LR"; // Liberia
    public static final String LY = "LY"; // Libya
    public static final String LI = "LI"; // Liechtenstein
    public static final String LT = "LT"; // Lithuania
    public static final String LU = "LU"; // Luxembourg
    public static final String MO = "MO"; // Macau
    public static final String MK = "MK"; // Macedonia
    public static final String MG = "MG"; // Madagascar
    public static final String MW = "MW"; // Malawi
    public static final String MY = "MY"; // Malaysia
    public static final String MV = "MV"; // Maldives
    public static final String ML = "ML"; // Mali
    public static final String MT = "MT"; // Malta
    public static final String MH = "MH"; // Marshall Islands
    public static final String MR = "MR"; // Mauritania
    public static final String MU = "MU"; // Mauritius
    public static final String YT = "YT"; // Mayotte
    public static final String MX = "MX"; // Mexico
    public static final String FM = "FM"; // Micronesia
    public static final String MD = "MD"; // Moldova
    public static final String MC = "MC"; // Monaco
    public static final String MN = "MN"; // Mongolia
    public static final String ME = "ME"; // Montenegro
    public static final String MS = "MS"; // Montserrat
    public static final String MA = "MA"; // Morocco
    public static final String MZ = "MZ"; // Mozambique
    public static final String MM = "MM"; // Myanmar
    public static final String NA = "NA"; // Namibia
    public static final String NR = "NR"; // Nauru
    public static final String NP = "NP"; // Nepal
    public static final String NL = "NL"; // Netherlands
    public static final String NC = "NC"; // New Caledonia
    public static final String NZ = "NZ"; // New Zealand
    public static final String NI = "NI"; // Nicaragua
    public static final String NE = "NE"; // Niger
    public static final String NG = "NG"; // Nigeria
    public static final String NU = "NU"; // Niue
    public static final String KP = "KP"; // North Korea
    public static final String MP = "MP"; // Northern Mariana Islands
    public static final String NO = "NO"; // Norway
    public static final String OM = "OM"; // Oman
    public static final String PK = "PK"; // Pakistan
    public static final String PW = "PW"; // Palau
    public static final String PS = "PS"; // Palestine
    public static final String PA = "PA"; // Panama
    public static final String PG = "PG"; // Papua New Guinea
    public static final String PY = "PY"; // Paraguay
    public static final String PE = "PE"; // Peru
    public static final String PH = "PH"; // Philippines
    public static final String PN = "PN"; // Pitcairn
    public static final String PL = "PL"; // Poland
    public static final String PT = "PT"; // Portugal
    public static final String PR = "PR"; // Puerto Rico
    public static final String QA = "QA"; // Qatar
    public static final String CG = "CG"; // Republic of the Congo
    public static final String RE = "RE"; // Reunion
    public static final String RO = "RO"; // Romania
    public static final String RU = "RU"; // Russia
    public static final String RW = "RW"; // Rwanda
    public static final String BL = "BL"; // Saint Barthelemy
    public static final String SH = "SH"; // Saint Helena
    public static final String KN = "KN"; // Saint Kitts and Nevis
    public static final String LC = "LC"; // Saint Lucia
    public static final String MF = "MF"; // Saint Martin
    public static final String PM = "PM"; // Saint Pierre and Miquelon
    public static final String VC = "VC"; // Saint Vincent and the Grenadines
    public static final String WS = "WS"; // Samoa
    public static final String SM = "SM"; // San Marino
    public static final String ST = "ST"; // Sao Tome and Principe
    public static final String SA = "SA"; // Saudi Arabia
    public static final String SN = "SN"; // Senegal
    public static final String RS = "RS"; // Serbia
    public static final String SC = "SC"; // Seychelles
    public static final String SL = "SL"; // Sierra Leone
    public static final String SG = "SG"; // Singapore
    public static final String SX = "SX"; // Sint Maarten
    public static final String SK = "SK"; // Slovakia
    public static final String SI = "SI"; // Slovenia
    public static final String SB = "SB"; // Solomon Islands
    public static final String SO = "SO"; // Somalia
    public static final String ZA = "ZA"; // South Africa
    public static final String KR = "KR"; // South Korea
    public static final String SS = "SS"; // South Sudan
    public static final String ES = "ES"; // Spain
    public static final String LK = "LK"; // Sri Lanka
    public static final String SD = "SD"; // Sudan
    public static final String SR = "SR"; // Suriname
    public static final String SJ = "SJ"; // Svalbard and Jan Mayen
    public static final String SZ = "SZ"; // Swaziland
    public static final String SE = "SE"; // Sweden
    public static final String CH = "CH"; // Switzerland
    public static final String SY = "SY"; // Syria
    public static final String TW = "TW"; // Taiwan
    public static final String TJ = "TJ"; // Tajikistan
    public static final String TZ = "TZ"; // Tanzania
    public static final String TH = "TH"; // Thailand
    public static final String TG = "TG"; // Togo
    public static final String TK = "TK"; // Tokelau
    public static final String TO = "TO"; // Tonga
    public static final String TT = "TT"; // Trinidad and Tobago
    public static final String TN = "TN"; // Tunisia
    public static final String TR = "TR"; // Turkey
    public static final String TM = "TM"; // Turkmenistan
    public static final String TC = "TC"; // Turks and Caicos Islands
    public static final String TV = "TV"; // Tuvalu
    public static final String UG = "UG"; // Uganda
    public static final String UA = "UA"; // Ukraine
    public static final String AE = "AE"; // United Arab Emirates
    public static final String GB = "GB"; // United Kingdom
    public static final String US = "US"; // United States
    public static final String UY = "UY"; // Uruguay
    public static final String UZ = "UZ"; // Uzbekistan
    public static final String VU = "VU"; // Vanuatu
    public static final String VA = "VA"; // Vatican
    public static final String VE = "VE"; // Venezuela
    public static final String VN = "VN"; // Vietnam
    public static final String WF = "WF"; // Wallis and Futuna
    public static final String EH = "EH"; // Western Sahara
    public static final String YE = "YE"; // Yemen
    public static final String ZM = "ZM"; // Zambia
    public static final String ZW = "ZW"; // Zimbabwe
}
